### PR TITLE
Reset to default locale

### LINKED ISSUE #853: Address flakey DeviceStoryComment spec
See https://app.circleci.com/pipelines/github/Safecast/safecastapi/1063/workflows/723033c2-d0bf-4e82-9102-ead2378dfa3b/jobs/1563/tests#failed-test-0 for example failure.

This test has been failing occasionally during runs from main and PRs.

### PR DESCRIPTION
**Pull request by eitoball**
Fixes #853

When locale is `:ja`, space between attribute name and message is removed.

TODO: i18n-ize error messages in `DeviceStoryComment`

### CODE REVIEW

File: spec/models/device_story_comment_spec.rb [hunk 1]
```diff
@@ -9,19 +9,35 @@
...
     end
 
     context 'with JSON file' do
-      let(:upload_file) { fixture_file_upload('files/device_stories.json') }
+      let(:upload_file) { file_upload('spec/fixtures/files/device_stories.json', 'application/json') }
 
       it 'should have attached image' do
         expect(comment.save).to be_falsey
+        # binding.pry
+        comment.errors.full_messages
```
Comment (matschaffer) [inline spec/models/device_story_comment_spec.rb:40]: Guessing these two lines don't need to be here right?

Comment (eitoball) [reply spec/models/device_story_comment_spec.rb]: Right. Thank you for catching.

File: spec/models/device_story_comment_spec.rb [hunk 2]
```diff
@@ -9,16 +9,30 @@
   describe '#save' do
     let(:comment) { described_class.new(image: upload_file, content: '_content_', user: user, device_story: device_story) }
 
+    def file_upload(src, content_type, binary: false)
```
Comment (matschaffer) [inline spec/models/device_story_comment_spec.rb:12]: Why do we need our own upload function? Seems like https://github.com/rails/rails/blob/v6.0.3.7/actionpack/lib/action_dispatch/testing/test_process.rb#L17 supports mime type definition.

Comment (matschaffer) [reply spec/models/device_story_comment_spec.rb:12]: Ah, nm. I see

Comment (matschaffer) [inline spec/models/device_story_comment_spec.rb:12]:
```suggestion
    # Workaround for ActiveStorage::IntegrityError, see https://github.com/rails/rails/issues/41991
    def file_upload(src, content_type, binary: false)
```

**Review by matschaffer — CHANGES_REQUESTED** [review]
Let's not the reason for the custom uploader just to avoid future confusion. Other than that LGTM

**Review by matschaffer — APPROVED** [review]
